title: Saiwas Blog
email: johnnysaiwas@gmail.com
description: >-
  A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.
baseurl: "/blog"
url: ""
github_username:  saiwas
permalink: /:categories/:title:output_ext

sass:
  style: compressed

# Build settings
markdown: kramdown

# Setting paginates
plugins:
  - jekyll-paginate-v2

#permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  permalink: '/page:num/'
  limit: 0

# Config server response header
webrick:
  headers:
    Link: </css/main.css>; rel=preload; as=style, </images/github-avatar.jpg>; rel=preload; as=image
    Cache-Control: public, max-age=31536000
