title: Saiwas -- Full Stack Developer
email: johnnysaiwas@gmail.com
description: >-
  A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.
baseurl: ""
url: ""
github_username:  saiwas
permalink: /:categories/:title:output_ext

sass:
  style: compressed

# Build settings
markdown: kramdown
